### ISSUE TITLE
Please clarify this is not really react native with relay out of the box

### ISSUE THREAD

**Issue by rturk** [lenaten/react-native-relay#10]
Hi @lenaten thanks for building and sharing this code. 

Can you please clarify: If I'm reading the docs correctly, although the repo name says that this will work out of the box is not necessary using react, react-native and relay sources. This example uses a fork from react-native, react and fbjs. Correct?

In the current version is it possible to integrate this to an existing RN app using the standard React and RN source?

**Comment by lenaten** [comment]
I mean you can start a new project with this repo, without the need to fix all the compatibility issues by yourself.
Integration with existing project could be tricky..

**Comment by holmesal** [comment]
Actually, integrating with an existing project wasn't that bad - here's what I did:
- `npm install react-native@0.8.0` and make sure everything works properly
- clone this repo and paste everything in `node_modules` into your project's `node_modules` directory, overwriting when necessary
- grab `scripts/` and `config.js` from this repo
- update the path in `scripts/babelRelayPlugin.js` to point to your `schema.json`

That worked for me. I had some issues with react packager naming collisions, but repeating the second step without the packager running seemed to fix it for me.

**Comment by lenaten** [comment]
Thanks for sharing.
