### ISSUE TITLE
Update versions of react-native and react-relay

### ISSUE THREAD

**Issue by macrostart** [lenaten/react-native-relay#4]
Currently this project's package.json lists react-native 0.13.0 and react-relay 0.4.0 . Current latest releases are: 0.16.0 and 0.6.0. Changelogs include breaking changes, new features and bug fixes. Would be nice to have them in this project too.

**Comment by lenaten** [comment]
Agree. Help is welcomed.

**Comment by lenaten** [comment]
closed by #6
